### ISSUE TITLE
Indigo release 0.7.1

### ISSUE THREAD

**Issue by 130s** [ros-gbp/moveit_ros-release#2]
I'm making a patch release of `moveit_ros` into Indigo (https://github.com/ros-planning/moveit_ros/issues/662) then realized that I don't have a write access to this repo. Could any admin take care of this? 
@sachinchitta

**Comment by 130s** [comment]
Maybe ROS organizers @wjwwood @tfoote can help?
I was asked offline earlier to help release tasks of MoveIt! by Sachin. @IanTheEngineer too if he's not given the write access yet.

**Comment by sachinchitta** [comment]
Not sure why but I don't have write access to grant you permission either. Can someone add me too?

**Comment by jackieokay** [comment]
I have added @130s to the ros-planning team, which should give him write access to this repository.

**Comment by 130s** [comment]
@jacquelinekay thank you, now bloom is going through the path.

Also as said above, could you add @sachinchitta and @IanTheEngineer?

**Comment by jackieokay** [comment]
Sachin and Ian are already in the ros-planning organization.

**Comment by sachinchitta** [comment]
Why can't I add people to ros-planning any more? Could you please restore my ability to do that?

**Comment by wjwwood** [comment]
@sachinchitta AFAICT you are an owner on `ros-planning`:

<img width="975" alt="screen shot 2016-04-12 at 12 12 57 pm" src="https://cloud.githubusercontent.com/assets/100427/14472415/fbd23e40-00a7-11e6-8207-3cb0b67975c3.png">

**Comment by wjwwood** [comment]
Maybe you mean `ros-gbp`?

**Comment by jackieokay** [comment]
I think he's talking about the ros-planning team in the ros-gbp organization.

I think we have to switch to the new fine-grained Github permissions in order for a user to be an admin for a particular team. I will work on this migration today (it's been in my backlog for a while).

**Comment by sachinchitta** [comment]
Sorry I meant ros-gbp/ros-planning

**Comment by wjwwood** [comment]
@sachinchitta can you check now? I made you a team maintainer on the ros-gbp/ros-planning team. At one point there was an issue when inviting someone who was not previously on the organization, but I think GitHub fixed that? We're still figuring out what will work best.

**Comment by sachinchitta** [comment]
I can see the "add a person" field but github tells me the person does not exist no matter whose name I add (even my own). Might be something to do with their new permissions settings.

**Comment by wjwwood** [comment]
I see, it sounds like GitHub still requires you to invite the person to the organization before adding them to a team. Can you try to add someone to the team who is a member of the organization, but not in the team currently? Like myself?

I'll look into the issue of not being able to invite someone to the organization.

**Comment by sachinchitta** [comment]
Nope - says @wjwwood is not a github member.

**Comment by wjwwood** [comment]
Hmm, well that's clearly not true :smile:. I'll try to figure out what's going on.

**Comment by wjwwood** [comment]
@sachinchitta I believe you now should be able to add people to the team that are already members of the organization, and you should be able to go to any single repository's settings, e.g. https://github.com/ros-gbp/moveit_ros-release/settings/collaboration, and add a "collaborator". It looks like only organization owners can add people as organization members, which is a prerequisite to being added to a team.

If you could confirm you can add people in the org to the team (like me or my alter-ego @wjwwood-snippets) and that you can add collaborators to individual repositories that would be great. I'm going to continue to look into other settings so we have a complete view of the options.
